### ISSUE TITLE
Setting property from outside not calling render

### ISSUE THREAD

**Issue by bennypowers** [kenchris/lit-element#17]
Setting a property from outside via assignment operator doesn't seem to be calling render
```js
import {LitElement, html} from './node_modules/lit-html-element/lit-element.js';

class TtcFtw extends LitElement {
  static get is() {return 'ttc-ftw';}
  static get properties() {
    return {
      stationName: {
        type: String,
      },
    };
  }

  render() {
    return html`<h1>${this.stationName}</h1>`;
  }
}

customElements.define(TtcFtw.is, TtcFtw)
```

Works:
```html
<input id="input" type="text" name="stationName" placeholder="Enter Station Name"/>
<ttc-ftw id="ttc"></ttc-ftw>
<script>
  input.onkeyup = event => {
    ttc.stationName = event.target.value;
    ttc.invalidate();
  }
</script>
```

Doesn't work:
```html
<input id="input" type="text" name="stationName" placeholder="Enter Station Name"/>
<ttc-ftw id="ttc"></ttc-ftw>
<script>
  input.onkeyup = event => ttc.stationName = event.target.value;
    // ttc.setAttribute('station-name', event.target.value); also doesn't

</script>
```

README.md Advanced section says that setting properties will cause a render. Please clarify in docs how that works. Cheers! 🍻

**Comment by kenchris** [comment]
You need to call `withProperties()``` when registering

```customElements.define(TtcFtw.is, TtcFtw)``` should be ```customElements.define(TtcFtw.is, TtcFtw.withProperties())```

Can you try that?

**Comment by bennypowers** [comment]
Ok saw that now. didn't notice in the docs. You might want to put a link in the advanced section for readers like me that try to skip to the juicy bits 😉 

Side note, polymer-ide complains 'unable to evaluate this expression down to a class reference' when I call that method in the definition.

Thanks again.

**Comment by kenchris** [comment]
Feel free to submit PRs to improve the docs or generate jsdocs from the TS files
