### ISSUE TITLE
Setting Array Property creates Array of Array

### ISSUE THREAD

**Issue by rogeru** [kenchris/lit-element#21]
When setting an array property, the code ```const value = typeFn(v);``` at https://github.com/kenchris/lit-element/blob/master/src/lit-element.ts#L57 wraps the array value into another array.

Should that code check ```Array.isArray``` and only convert if not already an array?

Example:
http://plnkr.co/edit/zHofw0jySY2avRK4yX2y?p=preview

**Comment by kenchris** [comment]
A good point! Could you submit a PR including tests? I assume this affects all non-primitive types such as Object etc as well

**Comment by rogeru** [comment]
Submitted a pull request. Object types are fine.

**Comment by kenchris** [comment]
Merged, closing

**Comment by rogeru** [comment]
@kenchris are you planning on releasing an update to npm that includes this fix?

**Comment by kenchris** [comment]
Sure, done :-)
