### ISSUE TITLE
types on propertyDeclaration

### ISSUE THREAD

**Issue by filipbech** [kenchris/lit-element#26]
If I understand this correctly we have a wrong type on properties.

Its not a an array of propertyDeclarations... its really an object with string keys and propertyDeclarations as values... correct? 

also computed should be optional as well, right?

I propose this

```ts
export interface PropertyDeclaration {
  type: (a: any) => any;
  value?: any;
  attrName?: string;
  computed?: string;
}

interface PropertyDeclarationMap {
  [key:string]: PropertyDeclaration;
}
```

and then
```ts
static get properties(): PropertyDeclarationMap {
    return {};
  }
```

Do you agree?

**Comment by kenchris** [comment]
Currently it is 

```
  static get properties(): Map<PropertyOptions> {
    return {};
  }
```

You must be looking at old code :)

**Comment by filipbech** [comment]
Thats weird... I just pulled from npm... npm-version not bumped?

**Comment by filipbech** [comment]
but yeah that looks fine

**Comment by kenchris** [comment]
Maybe I forgot... released
