### ISSUE TITLE
can't get the static method "withProperties" in custom class

### ISSUE THREAD

**Issue by minzojian** [kenchris/lit-element#28]
![image](https://user-images.githubusercontent.com/361781/35572341-5e442980-060f-11e8-9a1e-8ebcfc0dc5f4.png)

why?
it is a simple .ts file

**Comment by minzojian** [comment]
![image](https://user-images.githubusercontent.com/361781/35573252-813cacd0-0611-11e8-884d-9daf54c78613.png)
and this is just disgusting

**Comment by filipbech** [comment]
works on my machine... :-/ sorry...

Is typescript working in general... (do you get suggestions/autocomplete inside MyApp?  does it suggest invalidate as a method to call?

and what version of TS are you on?

**Comment by larsgk** [comment]
could it be an old type def for lit-element? (cleared cache, re-installed
from npm?)

On Tue, Jan 30, 2018 at 4:20 PM, Filip Bech-Larsen <notifications@github.com

**Comment by minzojian** [comment]
sorry guys,i may import a wrong js file. things going fine after i import the ts file inside the src folder
![image](https://user-images.githubusercontent.com/361781/35576254-7d7efe1a-0619-11e8-97b2-2d149ccb2f20.png)

**Comment by minzojian** [comment]
oh no, it just looks fine in ide, but still failed when did webpack compiling
![image](https://user-images.githubusercontent.com/361781/35576747-c1afe210-061a-11e8-9e41-c8dab1051514.png)

**Comment by minzojian** [comment]
at last, i copied the lit-element.d.ts out of src folder and placed it with the outer lit-element.js
then i add a reference, then it works at all
![image](https://user-images.githubusercontent.com/361781/35578116-221ee954-061e-11e8-9e47-7cb2a76fdf3f.png)
