### ISSUE TITLE
Provide example for bound Boolean properties & attributes

### ISSUE THREAD

**Issue by klebba** [kenchris/lit-element#4]
Example:

```
<my-element foo="${bar}"></my-element>
```

When `foo` has a property definition with type `Boolean`, Polymer would render this binding as:

`<my-element foo></my-element>`

When `bar` is truthy. Otherwise `foo` is removed. This is a necessary behavior for CSS selectors like:

```
<style>
:host([foo]) {
    color: red;
}
</style>
```

**Comment by kenchris** [comment]
Yes, I should fix that.

The following would be correct <div foo> or <div foo=""> or <div foo="foo"> or case-insensitive and single quotes/unquoted variations.
