### ISSUE TITLE
For discussion: maybe call the render-method with ´this´ as an argument

### ISSUE THREAD

**Issue by filipbech** [kenchris/lit-element#8]
**Usecase**: use parameter-destruturing to gain easier access to data. 

It would be a non-breaking new feature that would make it even more fun, and make using it even less verbose. 

## example

instead of 
```
render() {
    html`
        <div>${this.somebinding}</div>
    `
}
```

I could do
```
render({somebinding}) {
    html`
        <div>${somebinding}</div>
    `
}
```

Preact does this with props and state, and its pretty great to use... 

What do you think?

**Comment by kenchris** [comment]
Are there any downsides to this? I assume that I can keep using it with this.* if I wanted to.

I am not against it, so if there are no downsides and this is more familiar to react and preact users, then why not.

**Comment by filipbech** [comment]
I don't see any downsides... (it should be some engine-optimizations or memory issues if I had to guess)
It is actually only a feature of preact (not react) so maybe not as commonly used/known... but I sure like it...

**Comment by kenchris** [comment]
Want to give this a try?

**Comment by filipbech** [comment]
Ill consider it again, and implement it if I still like it :-D

**Comment by filipbech** [comment]
Ive thought about this some more and I think we should forget about it again...

**Comment by kenchris** [comment]
OK, could you state the reason behind it? :) Just interested to know why

**Comment by filipbech** [comment]
The idea was only developer convenience, and the implementation ended up complicating it for the types to work as expected.

**Comment by kenchris** [comment]
Complicated? It should be super easy to implement :-) Just check out my quick attempt

```
class T { 

  constructor() { this.hi = "yo"; }
  run() { this.render(this); } 
  render({ hi }) { console.log(hi); }
}

$ (new T).run()
> yo
```

**Comment by filipbech** [comment]
yeah, thats how it would eventually run, but TypeSCript doesn't support it this way - without the editor manually adding the expected type of the argument in render... and if it cant help us with the destructuring assignment we are worse off... 

The problem is that we cant specify the type for the argument being render() is being called with inside LitElement... and as such classes extending from LitElement cant automatically know what type the argument is...

**Comment by filipbech** [comment]
I tried messing around with generic types and stuff, but I might be missing something...

**Comment by filipbech** [comment]
```ts
class LitElement {
  render(arg: WHAT_TYPE_HERE) { ... }
}

class MyElement extends LitElement {
  render(THE ARGUMENT SHOULD AUTOMATICALLY BE OF TYPE MyElement) { ... }
}
```

**Comment by kenchris** [comment]
Well, we just need to add "this" to the render function when called, and then it should work fine from JS. Doesn't "any" work for that?

Whether people can actually use it from TS, is another case... we at least help the JS peeps :-)

**Comment by kenchris** [comment]
```
diff --git a/src/lit-element.ts b/src/lit-element.ts
index bc754b2..5d88179 100644
--- a/src/lit-element.ts
+++ b/src/lit-element.ts
@@ -110,9 +110,9 @@ export class LitElement extends HTMLElement {
 
   renderCallback() {
     if (this._resolved) {
-      render(this.render(), this.shadowRoot as ShadowRoot);
+      render(this.render(this), this.shadowRoot as ShadowRoot);
     } else {
-      const template = this.render().template;
+      const template = this.render(this).template;
       const rootNode = template.element.content;
       const walker = document.createTreeWalker(rootNode, NodeFilter.SHOW_ELEMENT, null as any, false);
 
@@ -133,7 +133,8 @@ export class LitElement extends HTMLElement {
     }
   }
 
-  render(): TemplateResult {
+  // @ts-ignore
+  render(self: any): TemplateResult {
     return html``;
   }
```

**Comment by kenchris** [comment]
OK, implemented with test:

https://github.com/kenchris/lit-element/commit/f0c1c93b6338e820cacc578ed393442850714182

**Comment by filipbech** [comment]
thats true... the implementation is pretty innocent...
